"""Rasterize digits 0-9 from a sans-serif TTF into 64px-tall monochrome bitmaps
and emit a C header compatible with Adafruit_GFX drawBitmap().

Usage:
    python tools/gen_oled_digits.py
"""

import os

from PIL import Image, ImageDraw, ImageFont

FONT_PATH = r"C:\Windows\Fonts\arial.ttf"
TARGET_HEIGHT = 64          # full OLED height
DIGITS = "0123456789"
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "include", "hw", "oled_font_digits.h")


def pick_font_size():
    """Largest font size where the tallest digit fits within TARGET_HEIGHT."""
    best = 10
    for size in range(20, 200):
        font = ImageFont.truetype(FONT_PATH, size)
        max_h = 0
        for d in DIGITS:
            bbox = font.getbbox(d)
            max_h = max(max_h, bbox[3] - bbox[1])
        if max_h <= TARGET_HEIGHT:
            best = size
        else:
            break
    return best


def main():
    size = pick_font_size()
    font = ImageFont.truetype(FONT_PATH, size)

    # Fixed (tabular) cell width = widest digit ink + small padding.
    cell_w = 0
    for d in DIGITS:
        bbox = font.getbbox(d)
        cell_w = max(cell_w, bbox[2] - bbox[0])
    cell_w += 4

    stride = (cell_w + 7) // 8
    glyph_bytes = stride * TARGET_HEIGHT

    arrays = []
    for d in DIGITS:
        bbox = font.getbbox(d)
        gw = bbox[2] - bbox[0]
        gh = bbox[3] - bbox[1]

        img = Image.new("L", (cell_w, TARGET_HEIGHT), 0)
        draw = ImageDraw.Draw(img)
        x = (cell_w - gw) // 2 - bbox[0]
        y = (TARGET_HEIGHT - gh) // 2 - bbox[1]
        draw.text((x, y), d, font=font, fill=255)

        px = img.load()
        data = [0] * glyph_bytes
        for yy in range(TARGET_HEIGHT):
            for xx in range(cell_w):
                if px[xx, yy] >= 128:
                    data[yy * stride + (xx // 8)] |= (0x80 >> (xx % 8))
        arrays.append(data)

    lines = []
    lines.append("#ifndef HW_OLED_FONT_DIGITS_H")
    lines.append("#define HW_OLED_FONT_DIGITS_H")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("// Auto-generated by tools/gen_oled_digits.py - do not edit by hand.")
    lines.append("// Sans-serif digits 0-9 rasterized from Arial for Adafruit drawBitmap().")
    lines.append("")
    lines.append(f"#define OLED_DIGIT_WIDTH   {cell_w}")
    lines.append(f"#define OLED_DIGIT_HEIGHT  {TARGET_HEIGHT}")
    lines.append(f"#define OLED_DIGIT_STRIDE  {stride}")
    lines.append("")
    lines.append(f"static const uint8_t kOledDigits[10][{glyph_bytes}] = {{")
    for d, data in zip(DIGITS, arrays):
        body = ", ".join(f"0x{b:02X}" for b in data)
        lines.append(f"    {{ {body} }}, // {d}")
    lines.append("};")
    lines.append("")
    lines.append("#endif // HW_OLED_FONT_DIGITS_H")
    lines.append("")

    out_path = os.path.normpath(OUTPUT)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print(f"font size = {size}, cell = {cell_w}x{TARGET_HEIGHT}, stride = {stride}")
    print(f"written {out_path}")


if __name__ == "__main__":
    main()
